spring:
  datasource:
    url: jdbc:mysql://mysql:3306/marketplace_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Prajwal123

  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: mailhog
    port: 1025

app:
  file:
    upload-dir: /app/uploads
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000"
